name: create release pull-request

on:
  release:
    types: [prereleased]

jobs:
  create-release-pull-request:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      USER_EMAIL: github-actions@users.noreply.github.com
      USER_NAME: github-actions

    steps:
      - run: |
          git config --global user.email "${USER_EMAIL}"
          git config --global user.name "${USER_NAME}"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: GITHUB_REF
        run: |
          TAG=${{ github.event.release.name }}
          TAG=$(echo $TAG | sed 's/[^0-9.]//g')
          echo $TAG
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Chart.yaml
        working-directory: helm
        run: |
          VER=$(egrep "^version: " Chart.yaml | cut -d ' ' -f 2)
          echo $VER
          echo "VER=${VER}" >> $GITHUB_ENV

      - name: push
        if: env.VER != env.TAG
        working-directory: helm
        run: |
          sed -i -e "s/version: ${VER}/version: ${TAG}/g" Chart.yaml
          git checkout main
          git add Chart.yaml
          git commit -m "Chart version ${TAG}"
          git push origin HEAD
