name: filters

on:
  issues:
    types:
      - labeled
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: list labels
        working-directory: .github
        run: |
          APPS=(
            test1
            test2
          )
          for app in ${APPS[@]}; do
            echo "$app:" >> filters.yaml
            echo "  - src/$app/**" >> filters.yaml
          done

      # どのファイルに変更があったか
      # https://github.com/dorny/paths-filter
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: .github/filters.yaml

      - name: list labels
        uses: actions/github-script@v6
        id: lebels
        with:
          script: |
            if (context) {
              console.log("context")
              console.log(JSON.stringify(context))
              if (context.steps) {
                console.log("context.steps")
                console.log(JSON.stringify(context.steps))
                if (context.steps.changes) {
                  console.log(context.steps.changes.outputs)
                }
              }
            }

      # - name: aaaaa
      #   run: |
      #     # echo ${{ steps.changes.outputs }}
      #     # echo ${{ fromJSON(steps.changes.outputs) }}
      #     echo ${{ steps.changes.outputs.changes }}

      - name: Run Python
        run: |
          echo ${{ steps.changes.outputs.changes }}
