name: filters

on:
  issues:
    types:
      - labeled
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # どのファイルに変更があったか
      # https://github.com/dorny/paths-filter
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: .github/filters.yaml

      - name: list labels
        uses: actions/github-script@v6
        id: lebels
        with:
          script: |
            if (context) {
              if (context.steps) {
                console.log(context.steps)
                if (context.steps.changes) {
                  console.log(context.steps.changes.outputs)
                }
              }
            console.log(steps.changes.outputs)
            }

      #
      # terraform plan
      #
      - name: echo
        run: |
          echo ${{ steps.changes.outputs }}
