name: filters

on:
  issues:
    types:
      - labeled
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: list labels
        run: |
          apps=(
            test1
            test2
          )

          filters=.github/filters.yaml

          for app in ${apps[@]}; do
            echo "$app:" >> $filters
            echo "  - src/$app/**" >> $filters
            echo "  - src/sample_1/**" >> $filters
          done

      # どのファイルに変更があったか
      # https://github.com/dorny/paths-filter
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: .github/filters.yaml

      - name: terraform
        run: |
          echo ${{ steps.changes.outputs.changes }}
          apps=( `echo ${{ steps.changes.outputs.changes }} | sed -e '/[,\[\]]//g'`)
          for app in ${apps[@]}; do
            echo $app
          done

      # - name: list labels
      #   uses: actions/github-script@v6
      #   id: lebels
      #   with:
      #     script: |
      #       if (context) {
      #         console.log("context")
      #         console.log(JSON.stringify(context))
      #         if (context.steps) {
      #           console.log("context.steps")
      #           console.log(JSON.stringify(context.steps))
      #           if (context.steps.changes) {
      #             console.log(context.steps.changes.outputs)
      #           }
      #         }
      #       }

      # - name: aaaaa
      #   run: |
      #     # echo ${{ steps.changes.outputs }}
      #     # echo ${{ fromJSON(steps.changes.outputs) }}
      #     echo ${{ steps.changes.outputs.changes }}
