name: python

on:
  push:
    branches: [main]
    paths: [src]
  pull_request:
    branches: [main]
    paths: [src]

jobs:
  python:
    name: python
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Get Python version
        run: python -V

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python
        working-directory: src
        run: |
          python python-sample.py
          gh release create "v1.0.0"
