name: python

on:
  # push:
  #   tags:
  #     - "v*"
  release:
    types: [published]

jobs:
  python:
    name: python
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Get Python version
        run: python -V

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python
        working-directory: src
        run: |
          python python-sample.py

      # # tag → release
      # # http://skawashima.com/blog/2019/12/github-actions-auto-release/
      # - name: Release
      #   run: |
      #     echo ${{ github.ref }}
      #     # gh release create ${{ github.ref }} --generate-notes

      # #     # Upload all tarballs in a directory as release assets
      # #     # $ gh release create v1.2.3 ./dist/*.tgz
